#!/bin/bash
/Users/zhuangyuren/pmd-bin-6.9.0/bin/run.sh pmd -d /Users/zhuangyuren/Documents/GitHub/vergilplus/src -R rulesets/java/quickstart.xml -f html -r /Users/zhuangyuren/Documents/GitHub/vergilplus/report/pmd_report.html -failOnViolation false
